"""Generate sim/models/x500_visual from PX4's x500_base: a replay prop with spinning propellers.

    python tools/make_visual_quad.py [--px4-dir ~/PX4-Autopilot] [--rotor-rad-s 25]

The body is kinematic and every link ignores gravity, so the model stays where the replay puts it,
while Gazebo's JointController spins each rotor joint at a constant rate. Mesh URIs still point at
model://x500_base, which is on GZ_SIM_RESOURCE_PATH through scripts/env.sh. The survey camera
frustum link is appended. Rotor spin directions follow the airframe (0 and 1 counter-clockwise,
2 and 3 clockwise).
"""

__author__ = "Frank Loewenich"
import argparse
import os
import re


def main():
    """Parse the command line and write the replay quad model."""
    ap = argparse.ArgumentParser()
    ap.add_argument("--px4-dir", default=os.path.expanduser(os.environ.get("PX4_DIR", "~/PX4-Autopilot")))
    ap.add_argument("--rotor-rad-s", type=float, default=25.0, help="rotor spin rate; about 0.8 rad per frame at 30 fps reads as fast rotation")
    ap.add_argument("--out", default="sim/models/x500_visual/model.sdf")
    a = ap.parse_args()
    src = open(os.path.join(a.px4_dir, "Tools", "simulation", "gz", "models", "x500_base", "model.sdf")).read()
    s = src
    s = re.sub(r"<model name=['\"]x500_base['\"]>", "<model name='x500_visual'>", s, count=1)
    s = re.sub(r"<static>false</static>", "<static>false</static>", s, count=1)
    s = s.replace("<gravity>true</gravity>", "<gravity>false</gravity>")
    s = re.sub(r"\s*<sensor name=[^>]*>.*?</sensor>", "", s, flags=re.S)      # no IMU, baro or GNSS on a prop
    # the body follows set_pose only: kinematic, so rotor reaction torques and contacts cannot move it
    s = s.replace('<link name="base_link">', '<link name="base_link">\n      <kinematic>true</kinematic>', 1)
    spin = {0: 1, 1: 1, 2: -1, 3: -1}
    plugins = "\n".join(
        f'''    <plugin filename="gz-sim-joint-controller-system" name="gz::sim::systems::JointController">
      <joint_name>rotor_{i}_joint</joint_name>
      <initial_velocity>{d * a.rotor_rad_s:.1f}</initial_velocity>
    </plugin>''' for i, d in spin.items())
    frustum = '''    <link name="frustum">
      <pose relative_to="base_link">0 0 -0.05 0 0 0</pose>
      <gravity>false</gravity>
      <visual name="frustum_fill">
        <geometry><mesh><uri>model://x500_visual/frustum.obj</uri></mesh></geometry>
        <material>
          <ambient>0.25 0.65 1.0 1</ambient>
          <diffuse>0.25 0.65 1.0 1</diffuse>
          <specular>0 0 0 1</specular>
        </material>
        <transparency>0.75</transparency>
        <double_sided>true</double_sided>
        <cast_shadows>false</cast_shadows>
      </visual>
    </link>
    <joint name="frustum_joint" type="fixed"><parent>base_link</parent><child>frustum</child></joint>'''
    header = '''<?xml version="1.0" encoding="UTF-8"?>
<!-- Author: Frank Loewenich. Generated by tools/make_visual_quad.py from PX4's x500_base (BSD-3). Do not edit by hand.
     Visual-only replay quad: kinematic body, no gravity, rotors spun by JointController, plus the
     survey camera frustum. scripts/replay_follow.py moves it along a logged trajectory. -->
'''
    body = s[s.index("<sdf"):]
    body = body.replace("</model>", plugins + "\n" + frustum + "\n  </model>", 1)
    open(a.out, "w").write(header + body)
    print(f"wrote {a.out}: {body.count('<link ')} links, {body.count('JointController')} rotor controllers")


if __name__ == "__main__":
    main()
