"""Generate a Gazebo world of white bowls on grass plus a JSON ground-truth manifest.

    python tools/make_world.py --name sparse --seed 1 --bowls 12 --field 120 80
    python tools/make_world.py --name dense  --seed 2 --bowls 60 --field 120 80

Writes sim/worlds/bowl_field_<name>.sdf and sim/worlds/bowl_field_<name>.json.
The JSON is the single source of truth for scoring. Positions are metres in the world
frame (ENU, origin at the takeoff point) with latitude and longitude derived from the
world's spherical coordinates. The origin is PX4's default SITL location, not a real
operating site.

Field extents are centred on the origin. Bowls are kept at least --min-sep metres apart
and at least 3 m from the field edge so the survey footprint always covers them.
"""
from __future__ import annotations

import argparse
import json
import math
import os
import random

ORIGIN_LAT = 47.397971057728974   # PX4 default SITL origin (Zurich)
ORIGIN_LON = 8.546163739800146
ORIGIN_ALT = 0.0
EARTH_R = 6371000.0
TEXTURE_TILE_M = 16.0             # one 4096 px grass texture tile covers this many metres (0.39 cm/px)
GROUND_SIZE_M = 400.0


def enu_to_latlon(x: float, y: float) -> tuple[float, float]:
    """Small-offset flat-earth conversion, good to millimetres at field scale."""
    lat = ORIGIN_LAT + math.degrees(y / EARTH_R)
    lon = ORIGIN_LON + math.degrees(x / (EARTH_R * math.cos(math.radians(ORIGIN_LAT))))
    return lat, lon


def place_bowls(n: int, w: float, h: float, min_sep: float, rng: random.Random, margin: float = 3.0):
    pts: list[tuple[float, float]] = []
    tries = 0
    while len(pts) < n:
        tries += 1
        if tries > 200000:
            raise SystemExit(f"could not place {n} bowls with min-sep {min_sep} in {w}x{h} m")
        x = rng.uniform(-w / 2 + margin, w / 2 - margin)
        y = rng.uniform(-h / 2 + margin, h / 2 - margin)
        if all(math.hypot(x - px, y - py) >= min_sep for px, py in pts):
            pts.append((round(x, 3), round(y, 3)))
    return pts


def ground_mesh(path: str) -> None:  # written into sim/models/grass_ground
    """A single quad with UVs that repeat the grass texture every TEXTURE_TILE_M metres."""
    half = GROUND_SIZE_M / 2
    rep = GROUND_SIZE_M / TEXTURE_TILE_M
    with open(path, "w") as f:
        f.write("# ground quad generated by tools/make_world.py\n")
        f.write(f"v -{half} -{half} 0\nv {half} -{half} 0\nv {half} {half} 0\nv -{half} {half} 0\n")
        f.write(f"vt 0 0\nvt {rep} 0\nvt {rep} {rep}\nvt 0 {rep}\nvn 0 0 1\n")
        f.write("f 1/1/1 2/2/1 3/3/1\nf 1/1/1 3/3/1 4/4/1\n")


GUI = """
    <gui fullscreen="false">
      <plugin filename="MinimalScene" name="3D View">
        <gz-gui><title>3D View</title><property type="bool" key="showTitleBar">false</property><property type="string" key="state">docked</property></gz-gui>
        <engine>ogre2</engine><scene>scene</scene>
        <ambient_light>0.4 0.4 0.4</ambient_light><background_color>0.8 0.8 0.8</background_color>
        <camera_pose>-20 0 12 0 0.5 0</camera_pose>
        <camera_clip><near>0.25</near><far>25000</far></camera_clip>
      </plugin>
      <plugin filename="GzSceneManager" name="Scene Manager"><gz-gui><property key="state" type="string">floating</property><property key="showTitleBar" type="bool">false</property></gz-gui></plugin>
      <plugin filename="InteractiveViewControl" name="Interactive view control"><gz-gui><property key="state" type="string">floating</property><property key="showTitleBar" type="bool">false</property></gz-gui></plugin>
      <plugin filename="CameraTracking" name="Camera Tracking"><gz-gui><property key="state" type="string">floating</property><property key="showTitleBar" type="bool">false</property></gz-gui></plugin>
      <plugin filename="WorldControl" name="World control">
        <gz-gui><title>World control</title><property type="bool" key="showTitleBar">false</property><property type="bool" key="resizable">false</property><property type="double" key="height">72</property><property type="double" key="width">121</property><property type="double" key="z">1</property><property type="string" key="state">floating</property>
          <anchors target="3D View"><line own="left" target="left"/><line own="bottom" target="bottom"/></anchors></gz-gui>
        <play_pause>true</play_pause><step>true</step><start_paused>true</start_paused>
      </plugin>
      <plugin filename="WorldStats" name="World stats">
        <gz-gui><title>World stats</title><property type="bool" key="showTitleBar">false</property><property type="bool" key="resizable">false</property><property type="double" key="height">110</property><property type="double" key="width">290</property><property type="double" key="z">1</property><property type="string" key="state">floating</property>
          <anchors target="3D View"><line own="right" target="right"/><line own="bottom" target="bottom"/></anchors></gz-gui>
        <sim_time>true</sim_time><real_time>true</real_time><real_time_factor>true</real_time_factor><iterations>true</iterations>
      </plugin>
      <plugin filename="ImageDisplay" name="Survey camera"><gz-gui><property key="state" type="string">docked</property></gz-gui><topic>/uav/camera</topic></plugin>
    </gui>
"""


def world_sdf(name: str, bowls) -> str:
    bowl_models = "\n".join(
        f'    <include><name>bowl_{i:03d}</name><uri>model://bowl</uri><pose>{x} {y} 0 0 0 0</pose></include>'
        for i, (x, y) in enumerate(bowls)
    )
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/make_world.py. Do not edit by hand: regenerate and keep the JSON in step. -->
<sdf version="1.9">
  <world name="{name}">
    <physics type="ode">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>250</real_time_update_rate>
    </physics>
    <plugin name="gz::sim::systems::Physics" filename="gz-sim-physics-system"/>
    <plugin name="gz::sim::systems::UserCommands" filename="gz-sim-user-commands-system"/>
    <plugin name="gz::sim::systems::SceneBroadcaster" filename="gz-sim-scene-broadcaster-system"/>
    <plugin name="gz::sim::systems::Contact" filename="gz-sim-contact-system"/>
    <plugin name="gz::sim::systems::Imu" filename="gz-sim-imu-system"/>
    <plugin name="gz::sim::systems::AirPressure" filename="gz-sim-air-pressure-system"/>
    <plugin name="gz::sim::systems::ApplyLinkWrench" filename="gz-sim-apply-link-wrench-system"/>
    <plugin name="gz::sim::systems::NavSat" filename="gz-sim-navsat-system"/>
    <plugin name="gz::sim::systems::Sensors" filename="gz-sim-sensors-system">
      <render_engine>ogre2</render_engine>
    </plugin>
{GUI}
    <gravity>0 0 -9.8</gravity>
    <magnetic_field>6e-06 2.3e-05 -4.2e-05</magnetic_field>
    <atmosphere type="adiabatic"/>
    <scene>
      <grid>false</grid>
      <ambient>0.8 0.8 0.8 1</ambient>
      <background>0.7 0.8 1 1</background>
      <shadows>true</shadows>
    </scene>
    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 100 0 0 0</pose>
      <intensity>1.6</intensity>
      <diffuse>1 1 0.95 1</diffuse>
      <specular>0.3 0.3 0.3 1</specular>
      <direction>-0.4 0.3 -0.85</direction>
    </light>
    <include><uri>model://grass_ground</uri></include>
{bowl_models}
    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <world_frame_orientation>ENU</world_frame_orientation>
      <latitude_deg>{ORIGIN_LAT}</latitude_deg>
      <longitude_deg>{ORIGIN_LON}</longitude_deg>
      <elevation>{ORIGIN_ALT}</elevation>
    </spherical_coordinates>
  </world>
</sdf>
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--name", required=True, help="suffix for bowl_field_<name>")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--bowls", type=int, default=12)
    ap.add_argument("--field", type=float, nargs=2, default=(120.0, 80.0), metavar=("W", "H"), help="field size in metres, centred on the origin")
    ap.add_argument("--min-sep", type=float, default=2.0, help="minimum bowl spacing in metres")
    ap.add_argument("--out-dir", default="sim/worlds")
    a = ap.parse_args()

    rng = random.Random(a.seed)
    bowls = place_bowls(a.bowls, a.field[0], a.field[1], a.min_sep, rng)
    os.makedirs(a.out_dir, exist_ok=True)
    ground_mesh(os.path.join(os.path.dirname(a.out_dir.rstrip("/")), "models", "grass_ground", "ground_400m.obj"))
    world_name = f"bowl_field_{a.name}"
    # model:// URIs resolve through GZ_SIM_RESOURCE_PATH, which scripts/env.sh points at sim/models
    sdf = world_sdf(world_name, bowls)
    with open(os.path.join(a.out_dir, world_name + ".sdf"), "w") as f:
        f.write(sdf)
    manifest = {
        "world": world_name,
        "seed": a.seed,
        "field_m": list(a.field),
        "origin": {"lat": ORIGIN_LAT, "lon": ORIGIN_LON, "alt": ORIGIN_ALT},
        "bowl_diameter_m": 0.16,
        "density_per_ha": round(a.bowls / (a.field[0] * a.field[1] / 10000.0), 3),
        "bowls": [
            {"id": i, "x": x, "y": y, **dict(zip(("lat", "lon"), enu_to_latlon(x, y)))}
            for i, (x, y) in enumerate(bowls)
        ],
    }
    with open(os.path.join(a.out_dir, world_name + ".json"), "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"wrote {world_name}.sdf and .json: {a.bowls} bowls on {a.field[0]:.0f}x{a.field[1]:.0f} m "
          f"({manifest['density_per_ha']} per ha)")


if __name__ == "__main__":
    main()
