"""Write the survey camera's view frustum as an OBJ pyramid for the replay quad.

    python tools/make_frustum.py --out sim/models/x500_visual/frustum.obj --length 60

Apex at the origin (the camera), axis along -z in the model frame, half-angles from the camera's
70 deg horizontal FOV and 4:3 aspect. Image right is body -y and image down is body -x, so the
base is 2*L*tan(hfov/2) across-track (y) by 2*L*tan(vfov/2) along-track (x). Long enough to pass
below the ground, whose opaque surface hides the buried part, so the visible frustum ends at the
true footprint at any altitude.
"""
import argparse
import math


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="sim/models/x500_visual/frustum.obj")
    ap.add_argument("--length", type=float, default=60.0)
    ap.add_argument("--hfov-deg", type=float, default=70.0)
    ap.add_argument("--aspect", type=float, default=4 / 3)
    a = ap.parse_args()
    L = a.length
    hy = L * math.tan(math.radians(a.hfov_deg) / 2)            # across-track half-width (body y)
    hx = hy / a.aspect                                          # along-track half-length (body x)
    v = [(0, 0, 0), (hx, hy, -L), (-hx, hy, -L), (-hx, -hy, -L), (hx, -hy, -L)]
    faces = [(1, 2, 3), (1, 3, 4), (1, 4, 5), (1, 5, 2), (2, 5, 4), (2, 4, 3)]
    with open(a.out, "w") as f:
        f.write("# camera frustum generated by tools/make_frustum.py\n")
        for x, y, z in v:
            f.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")
        for tri in faces:
            f.write("f " + " ".join(str(i) for i in tri) + "\n")
    print(f"wrote {a.out}: base {2*hx:.1f} x {2*hy:.1f} m at {L} m")


if __name__ == "__main__":
    main()
